require("keymaps.core")
require("keymaps.telescope")
require("keymaps.buffers")
require("keymaps.terminal")
require("keymaps.git")
require("keymaps.plugins")
require("keymaps.startify")
require("keymaps.json")
require("keymaps.lualine")
require("keymaps.neotree")
-- require("keymaps.lspzero")
