--Startify lua
local opts = { noremap = true, silent = true }
vim.api.nvim_set_keymap('n', '<leader>st', ':Startify<CR>', opts)

vim.g.startify_custom_header = {
  -- [[                                                                                                                      ]],
  -- [[                                                                                                                      ]],
  -- [[        CCCCCCCCCCCCChhhhhhh                                                 hhhhhhh                                  ]],
  -- [[     CCC::::::::::::Ch:::::h                                                 h:::::h                                  ]],
  -- [[   CC:::::::::::::::Ch:::::h                                                 h:::::h                                  ]],
  -- [[  C:::::CCCCCCCC::::Ch:::::h                                                 h:::::h                                  ]],
  -- [[ C:::::C       CCCCCC h::::h hhhhh          ooooooooooo       cccccccccccccccch::::h hhhhh   yyyyyyy           yyyyyyy]],
  -- [[C:::::C               h::::hh:::::hhh     oo:::::::::::oo   cc:::::::::::::::ch::::hh:::::hhh y:::::y         y:::::y ]],
  -- [[C:::::C               h::::::::::::::hh  o:::::::::::::::o c:::::::::::::::::ch::::::::::::::hhy:::::y       y:::::y  ]],
  -- [[C:::::C               h:::::::hhh::::::h o:::::ooooo:::::oc:::::::cccccc:::::ch:::::::hhh::::::hy:::::y     y:::::y   ]],
  -- [[C:::::C               h::::::h   h::::::ho::::o     o::::oc::::::c     ccccccch::::::h   h::::::hy:::::y   y:::::y    ]],
  -- [[C:::::C               h:::::h     h:::::ho::::o     o::::oc:::::c             h:::::h     h:::::h y:::::y y:::::y     ]],
  -- [[C:::::C               h:::::h     h:::::ho::::o     o::::oc:::::c             h:::::h     h:::::h  y:::::y:::::y      ]],
  -- [[ C:::::C       CCCCCC h:::::h     h:::::ho::::o     o::::oc::::::c     ccccccch:::::h     h:::::h   y:::::::::y       ]],
  -- [[  C:::::CCCCCCCC::::C h:::::h     h:::::ho:::::ooooo:::::oc:::::::cccccc:::::ch:::::h     h:::::h    y:::::::y        ]],
  -- [[   CC:::::::::::::::C h:::::h     h:::::ho:::::::::::::::o c:::::::::::::::::ch:::::h     h:::::h     y:::::y         ]],
  -- [[     CCC::::::::::::C h:::::h     h:::::h oo:::::::::::oo   cc:::::::::::::::ch:::::h     h:::::h    y:::::y          ]],
  -- [[        CCCCCCCCCCCCC hhhhhhh     hhhhhhh   ooooooooooo       cccccccccccccccchhhhhhh     hhhhhhh   y:::::y           ]],
  -- [[                                                                                                   y:::::y            ]],
  -- [[                                                                                                  y:::::y             ]],
  -- [[                                                                                                 y:::::y              ]],
  -- [[                                                                                                y:::::y               ]],
  -- [[                                                                                               yyyyyyy                ]],
  -- [[                                                                                                                      ]],
  -- [[                                                                                                                      ]],
  [[  ______                             __                      __           ]],
  [[ /      \                           |  \                    |  \          ]],
  [[|  $$$$$$\  ______    ______    ____| $$  ______    _______  \$$  _______ ]],
  [[| $$   \$$ |      \  /      \  /      $$ /      \  /       \|  \ /       \]],
  [[| $$        \$$$$$$\|  $$$$$$\|  $$$$$$$|  $$$$$$\|  $$$$$$$| $$|  $$$$$$$]],
  [[| $$   __  /      $$| $$  | $$| $$  | $$| $$    $$ \$$    \ | $$ \$$    \ ]],
  [[| $$__/  \|  $$$$$$$| $$__/ $$| $$__| $$| $$$$$$$$ _\$$$$$$\| $$ _\$$$$$$\ ]],
  [[ \$$    $$ \$$    $$| $$    $$ \$$    $$ \$$     \|       $$| $$|       $$]],
  [[  \$$$$$$   \$$$$$$$| $$$$$$$   \$$$$$$$  \$$$$$$$ \$$$$$$$  \$$ \$$$$$$$ ]],
  [[                    | $$                                                  ]],
  [[                    | $$                                                  ]],
  [[                     \$$                                                  ]],
  [[                                                                       ]],
  [[                                                                      ]],
  [[                   Bienvenido Chochy                   ]],
  [[                                                     ]],
}

